CREATE TABLE property_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL,
    media_kind VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL,
    alt_text VARCHAR(500),
    uploaded_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_property_media_property
        FOREIGN KEY (property_id) REFERENCES property_listing(id) ON DELETE CASCADE,
    CONSTRAINT fk_property_media_uploaded_by
        FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id),
    CONSTRAINT ck_property_media_kind
        CHECK (media_kind IN ('IMAGE', 'FLOOR_PLAN'))
);

CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_media_id BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    relative_url VARCHAR(600) NOT NULL,
    original_filename VARCHAR(255),
    content_type VARCHAR(120) NOT NULL,
    byte_size BIGINT NOT NULL,
    width INTEGER,
    height INTEGER,
    variant_type VARCHAR(32) NOT NULL,
    media_kind VARCHAR(32) NOT NULL,
    uploaded_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_media_assets_property_media
        FOREIGN KEY (property_media_id) REFERENCES property_media(id) ON DELETE CASCADE,
    CONSTRAINT fk_media_assets_property
        FOREIGN KEY (property_id) REFERENCES property_listing(id) ON DELETE CASCADE,
    CONSTRAINT fk_media_assets_uploaded_by
        FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id),
    CONSTRAINT uq_media_assets_storage_key UNIQUE (storage_key),
    CONSTRAINT uq_media_assets_media_variant UNIQUE (property_media_id, variant_type),
    CONSTRAINT ck_media_assets_variant
        CHECK (variant_type IN ('ORIGINAL', 'SMALL', 'MEDIUM', 'BIG')),
    CONSTRAINT ck_media_assets_kind
        CHECK (media_kind IN ('IMAGE', 'FLOOR_PLAN'))
);

CREATE INDEX idx_property_media_property_kind_active
    ON property_media(property_id, media_kind, deleted_at, sort_order);

CREATE INDEX idx_media_assets_property_media_active
    ON media_assets(property_media_id, deleted_at);

CREATE INDEX idx_media_assets_property_kind
    ON media_assets(property_id, media_kind);
